version: '2.1'
services:
  cloud_mysql:
    image: mysql:5.7.25
    restart: always
    ports:
      - 3306:3306
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    environment:
        MYSQL_ROOT_PASSWORD: root

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: cloud/config:0.0.1
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: cloud/registry:0.0.1
    restart: always
    depends_on:
      - config
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  zipkin:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: cloud/zipkin:0.0.1
    restart: always
    depends_on:
      - config
      - registry
    ports:
      - 9994:9994
    logging:
      options:
        max-size: "10m"
        max-file: "10"

